---

default: &default
  primary_user:
    username: <%= ENV['CUCUMBER_PRIMARY_USERNAME'] || 'local' %>
    password: <%= ENV['CUCUMBER_PRIMARY_PASSWORD'] || 'development' %>
    given_name: <%= ENV['CUCUMBER_PRIMARY_GIVEN_NAME'] || ENV['CUCUMBER_PRIMARY_USERNAME'] || 'local' %>
  signer_advances_user:
    username: <%= ENV['CUCUMBER_SIGNER_ADVANCES_USERNAME'] || 'local' %>
    password: <%= ENV['CUCUMBER_SIGNER_ADVANCES_PASSWORD'] || 'development' %>
  non_signer_advances_user:
    username: <%= ENV['CUCUMBER_NON_SIGNER_ADVANCES_USERNAME'] || 'local-non-signer' %>
    password: <%= ENV['CUCUMBER_NON_SIGNER_ADVANCES_PASSWORD'] || 'development' %>
  extranet_user:
    username: <%= ENV['CUCUMBER_EXTRANET_USERNAME'] || 'extra' %>
    password: <%= ENV['CUCUMBER_EXTRANET_PASSWORD'] || 'development' %>
  access_manager:
    username: <%= ENV['CUCUMBER_ACCESS_MANAGER_USERNAME'] || 'extra-chaste-access' %>
    password: <%= ENV['CUCUMBER_ACCESS_MANAGER_PASSWORD'] || 'development' %>
  deletable:
    username: <%= ENV['CUCUMBER_DELETABLE_USERNAME'] || 'extra-chaste-delete' %>
    password: <%= ENV['CUCUMBER_DELETABLE_PASSWORD'] || 'development' %>
  resetable:
    username: <%= ENV['CUCUMBER_RESETABLE_USERNAME'] || 'extra-chaste-reset' %>
    password: <%= ENV['CUCUMBER_RESETABLE_PASSWORD'] || 'development' %>
  expired:
    username: <%= ENV['CUCUMBER_EXPIRED_USERNAME'] || 'local-expired' %>
    password: <%= ENV['CUCUMBER_EXPIRED_PASSWORD'] || 'development' %>
  password_changable:
    username: <%= ENV['CUCUMBER_PASSWORD_CHANGE_USERNAME'] || 'local-password' %>
    password: <%= ENV['CUCUMBER_PASSWORD_CHANGE_PASSWORD'] || 'development' %>
  extranet_no_role:
    username: <%= ENV['CUCUMBER_EXTRANET_NOROLE_USERNAME'] || 'extra-chaste-norole' %>
    password: <%= ENV['CUCUMBER_EXTRANET_NOROLE_PASSWORD'] || 'development' %>
  offsite:
    username: <%= ENV['CUCUMBER_OFFSITE_USERNAME'] || 'local-offsite' %>
    password: <%= ENV['CUCUMBER_OFFSITE_PASSWORD'] || 'development' %>
  advances_disabled:
    username: <%= ENV['CUCUMBER_OFFSITE_USERNAME'] || 'quick-advance-disabled' %>
    password: <%= ENV['CUCUMBER_OFFSITE_PASSWORD'] || 'development' %>
  primary_bank: <%= ENV['CUCUMBER_PRIMARY_BANK'] || 'Meridian Bank, National Association' %>
  valid_password: <%= ENV['CUCUMBER_VALID_PASSWORD'] || '123Abcd3!' %>

local:
  <<: *default
  primary_bank: <%= ENV['CUCUMBER_PRIMARY_BANK'] || 'Wells Faygo' %>
dev:
  <<: *default

test:
  <<: *default

production:
  <<: *default

# insert configs once known
#qa:
#  app_host: 'qa.foo.com'
#  user1:
#    username:
#    password:
#
#staging:
#  app_host: 'stg.foo.com'
#  user1:
#    username:
#    password:
#
#production:
#  app_host: 'www.foo.com'
#  user1:
#    username:
#    password: