---

default: &default
  primary_user:
    username: <%= ENV['CUCUMBER_PRIMARY_USERNAME'] || 'local' %>
    password: <%= ENV['CUCUMBER_PRIMARY_PASSWORD'] || 'development' %>
  signer_advances_user:
    username: <%= ENV['CUCUMBER_SIGNER_ADVANCES_USERNAME'] || 'local' %>
    password: <%= ENV['CUCUMBER_SIGNER_ADVANCES_PASSWORD'] || 'development' %>
  non_signer_advances_user:
    username: <%= ENV['CUCUMBER_NON_SIGNER_ADVANCES_USERNAME'] || 'local-non-signer' %>
    password: <%= ENV['CUCUMBER_NON_SIGNER_ADVANCES_PASSWORD'] || 'development' %>
  extranet_user:
    username: <%= ENV['CUCUMBER_EXTRANET_USERNAME'] || 'extra' %>
    password: <%= ENV['CUCUMBER_EXTRANET_PASSWORD'] || 'development' %>
  access_manager:
    username: <%= ENV['CUCUMBER_ACCESS_MANAGER_USERNAME'] || 'extra-chaste-access' %>
    password: <%= ENV['CUCUMBER_ACCESS_MANAGER_PASSWORD'] || 'development' %>
  primary_bank: <%= ENV['CUCUMBER_PRIMARY_BANK'] || 'Meridian Bank, National Association' %>

local:
  <<: *default
  primary_bank: <%= ENV['CUCUMBER_PRIMARY_BANK'] || 'Wells Faygo' %>

dev:
  <<: *default

test:
  <<: *default

production:
  <<: *default

# insert configs once known
#qa:
#  app_host: 'qa.foo.com'
#  user1:
#    username:
#    password:
#
#staging:
#  app_host: 'stg.foo.com'
#  user1:
#    username:
#    password:
#
#production:
#  app_host: 'www.foo.com'
#  user1:
#    username:
#    password: